server:
  port: 8084

spring:
  application:
    name: ITicket
  profiles:
    active: prod
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ITicket
    username: admin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  jackson:
    serialization:
      fail-on-empty-beans: false